services:
  node:
    container_name: node-container
    hostname: node-container
    image: node:14
    build: .
    restart: always
    ports:
      - 8080:3000
    networks:
      - cluster
    volumes:
      - ~/uploads:/usr/src/app/public/uploads
    environment:
     - NODE_ENV=production

networks:
  cluster:
    external: true
