'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => queryInterface.bulkInsert(
    'Students',
    [
      {
        email:'simongrove@gmail.com',
        password: '$2b$10$RZMS0Th.ntmF7xuaUYmARO8AZdpX6PpmUWgmeR0DsnMXqtS8gE7.G',
        fornavn: 'Simon',
        efternavn: 'Grove',
        tlfnr: 22287964,
        foedselsdato: new Date(1999,1,18),
        createdAt: new Date(),
        updatedAt: new Date(),
      },{
        email:'benkyhn@gmail.com',
        password: '$2b$10$RZMS0Th.ntmF7xuaUYmARO8AZdpX6PpmUWgmeR0DsnMXqtS8gE7.G',
        fornavn: 'Benjamin',
        efternavn: 'Kyhn',
        tlfnr: 22287965,
        foedselsdato: new Date(1988,4,15),
        createdAt: new Date(),
        updatedAt: new Date(),
      },{
        email:'matiaslys@gmail.com',
        password: '$2b$10$RZMS0Th.ntmF7xuaUYmARO8AZdpX6PpmUWgmeR0DsnMXqtS8gE7.G',
        fornavn: 'Matias',
        efternavn: 'Lys',
        tlfnr: 22287966,
        foedselsdato: new Date(1999,4,15),
        createdAt: new Date(),
        updatedAt: new Date(),
      },{
        email:'kelvinaggerholm@gmail.com',
        password: '$2b$10$RZMS0Th.ntmF7xuaUYmARO8AZdpX6PpmUWgmeR0DsnMXqtS8gE7.G',
        fornavn: 'Kelvin',
        efternavn: 'Aggerholm',
        tlfnr: 22287967,
        foedselsdato: new Date(1999,4,15),
        createdAt: new Date(),
        updatedAt: new Date(),
      },{
        email:'andersbille@gmail.com',
        password: '$2b$10$RZMS0Th.ntmF7xuaUYmARO8AZdpX6PpmUWgmeR0DsnMXqtS8gE7.G',
        fornavn: 'Anders',
        efternavn: 'Bille',
        tlfnr: 22287968,
        foedselsdato: new Date(1999,4,15),
        createdAt: new Date(),
        updatedAt: new Date(),
      },{
        email:'rasmusjannerup@gmail.com',
        password: '$2b$10$RZMS0Th.ntmF7xuaUYmARO8AZdpX6PpmUWgmeR0DsnMXqtS8gE7.G',
        fornavn: 'Rasmus',
        efternavn: 'Jannerup',
        tlfnr: 22287969,
        foedselsdato: new Date(1999,4,15),
        createdAt: new Date(),
        updatedAt: new Date(),
      },{
        email:'tommyhansen@gmail.com',
        password: '$2b$10$RZMS0Th.ntmF7xuaUYmARO8AZdpX6PpmUWgmeR0DsnMXqtS8gE7.G',
        fornavn: 'Tommy',
        efternavn: 'Hansen',
        tlfnr: 22287965,
        foedselsdato: new Date(1999,4,15),
        createdAt: new Date(),
        updatedAt: new Date(),
      },{
        email:'nickihvolgaard@gmail.com',
        password: '$2b$10$RZMS0Th.ntmF7xuaUYmARO8AZdpX6PpmUWgmeR0DsnMXqtS8gE7.G',
        fornavn: 'Nicki',
        efternavn: 'Hvolgaard',
        tlfnr: 22287965,
        foedselsdato: new Date(1999,4,15),
        createdAt: new Date(),
        updatedAt: new Date(),
      },{
        email:'sunebro@gmail.com',
        password: '$2b$10$RZMS0Th.ntmF7xuaUYmARO8AZdpX6PpmUWgmeR0DsnMXqtS8gE7.G',
        fornavn: 'Sune',
        efternavn: 'Bro',
        tlfnr: 22287965,
        foedselsdato: new Date(1999,4,15),
        createdAt: new Date(),
        updatedAt: new Date(),
      },{
        email:'nikolajthor@gmail.com',
        password: '$2b$10$RZMS0Th.ntmF7xuaUYmARO8AZdpX6PpmUWgmeR0DsnMXqtS8gE7.G',
        fornavn: 'Nikolaj',
        efternavn: 'Thor',
        tlfnr: 22287965,
        foedselsdato: new Date(1999,4,15),
        createdAt: new Date(),
        updatedAt: new Date(),
      },{
        email:'tokelund@gmail.com',
        password: '$2b$10$RZMS0Th.ntmF7xuaUYmARO8AZdpX6PpmUWgmeR0DsnMXqtS8gE7.G',
        fornavn: 'Toke',
        efternavn: 'Lund',
        tlfnr: 22287965,
        foedselsdato: new Date(1999,4,15),
        createdAt: new Date(),
        updatedAt: new Date(),
      },{
        email:'mikpedersen@gmail.com',
        password: '$2b$10$RZMS0Th.ntmF7xuaUYmARO8AZdpX6PpmUWgmeR0DsnMXqtS8gE7.G',
        fornavn: 'Mik',
        efternavn: 'Pedersen',
        tlfnr: 22287965,
        foedselsdato: new Date(1999,4,15),
        createdAt: new Date(),
        updatedAt: new Date(),
      },{
        email:'patrickpetersen@gmail.com',
        password: '$2b$10$RZMS0Th.ntmF7xuaUYmARO8AZdpX6PpmUWgmeR0DsnMXqtS8gE7.G',
        fornavn: 'Patrick',
        efternavn: 'Petersen',
        tlfnr: 22287965,
        foedselsdato: new Date(1999,4,15),
        createdAt: new Date(),
        updatedAt: new Date(),
      },{
        email:'danielsikorski@gmail.com',
        password: '$2b$10$RZMS0Th.ntmF7xuaUYmARO8AZdpX6PpmUWgmeR0DsnMXqtS8gE7.G',
        fornavn: 'Daniel',
        efternavn: 'Sikorski',
        tlfnr: 22287965,
        foedselsdato: new Date(1999,4,15),
        createdAt: new Date(),
        updatedAt: new Date(),
      },{
        email:'emilsølyst@gmail.com',
        password: '$2b$10$RZMS0Th.ntmF7xuaUYmARO8AZdpX6PpmUWgmeR0DsnMXqtS8gE7.G',
        fornavn: 'Emil',
        efternavn: 'Sølyst',
        tlfnr: 22287965,
        foedselsdato: new Date(1999,4,15),
        createdAt: new Date(),
        updatedAt: new Date(),
      }
    ],
    {},
  ),

  down: (queryInterface, Sequelize) => queryInterface.bulkDelete('Students', null, {}),
};

