version: '3'

services:
  db:
    container_name: db
    hostname: db
    image: mariadb
    ports:
      - 3306:3306
    networks:
      - cluster
    environment:
      MYSQL_ROOT_PASSWORD: changeMe

networks:
  cluster:
