services:
  db:
    container_name: database
    hostname: database
    image: mariadb
    ports:
      - 3306:3306
    networks:
      - cluster
    environment:
      MYSQL_ROOT_PASSWORD: {DB_PW}
      MYSQL_DATABASE: ZealandConnect

networks:
  cluster:
    external: true
