name: Docker

on:
  push:
    branches: master

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./nodes
          file: ./nodes/Dockerfile
          push: true
          tags: zealandconnect/zealandconnect:latest
          
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [push_to_registry]
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |  
          # Stop running container.
          docker stop node-container

          # Remove old container.
          docker rm node-container
          
          # Remove old image.
          docker rmi zealandconnect/zealandconnect	
          
          # pull newest image.
          docker pull zealandconnect/zealandconnect

          # Run a new container from a new image and mount upload folder on VM inside the container and set NODE_ENV to production.
          docker run -d --restart always -e NODE_ENV="production" --name node-container --network cluster -p 8080:3000 -v ~/uploads:/usr/src/app/public/uploads zealandconnect/zealandconnect
          
          # Tigger DB updates if there are any.
          docker exec -d node-container npx sequelize-cli db:migrate --env production
