name: Docker

on:
  push:
    branches: master

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./nodes
          file: ./nodes/Dockerfile
          push: true
          tags: zealandconnect/zealandconnect:latest
  
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [push_to_registry]
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |  
          # Stop running container
          docker stop live

          # Remove old container
          docker rm live
          
          # pull newest image
          docker pull zealandconnect/zealandconnect

          # Run a new container from a new image
          docker run -d --restart always --name live -p 80:3000 zealandconnect/zealandconnect
